import streamlit as st
import google.generativeai as genai
import os
import base64
import time
import re
from PIL import Image # इमेज को प्रोसेस करने के लिए ज़रूरी

# --- 0. SESSION STATE SETUP (मेमोरी सेटअप) ---
# यह सुनिश्चित करता है कि जब हम बटन दबाएं तो पुराना डेटा गायब न हो
if 'manual_text_content' not in st.session_state:
    st.session_state.manual_text_content = ""
if 'manual_uploaded_images' not in st.session_state:
    st.session_state.manual_uploaded_images = []

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(page_title="PaperBanao.ai", page_icon="📄", layout="wide")

# --- 2. CUSTOM CSS ---
st.markdown("""
<style>
    .main-header { font-size: 42px; color: #1E88E5; text-align: center; font-weight: bold; font-family: sans-serif; }
    .stButton>button { background-color: #1E88E5; color: white; font-size: 18px; width: 100%; border-radius: 8px; }
    .diagram-box { border: 2px dashed #1E88E5; padding: 15px; border-radius: 10px; background-color: #f0f8ff; margin-bottom: 20px;}
</style>
""", unsafe_allow_html=True)

# --- 3. HELPER FUNCTIONS ---
def get_image_base64(image_input):
    if not image_input: return None
    try:
        # Check if it's a PIL Image (from AI Generator)
        if isinstance(image_input, Image.Image):
            from io import BytesIO
            buffered = BytesIO()
            image_input.save(buffered, format="PNG")
            bytes_data = buffered.getvalue()
        # Check if it's a file path (str)
        elif isinstance(image_input, str):
            if os.path.exists(image_input):
                with open(image_input, "rb") as f: bytes_data = f.read()
            else: return None
        # Check if it's uploaded file object
        else:
            bytes_data = image_input.getvalue()
            
        base64_str = base64.b64encode(bytes_data).decode()
        return f"data:image/png;base64,{base64_str}"
    except Exception as e:
        print(f"Image Error: {e}")
        return None

def process_manual_text_auto_number(text, start_num):
    """Splits text by double newlines and assigns Q numbers automatically."""
    if not text: return ""
    raw_questions = re.split(r'\n\s*\n', text)
    formatted_html_parts = []
    current_q_num = start_num
    
    for q_block in raw_questions:
        q_block = q_block.strip()
        if not q_block: continue
        lines = q_block.split('\n')
        first_line = lines[0].strip()
        # Remove existing numbering attempts
        first_line = re.sub(r'^(Q\d+[.)]|\d+[.)]|Q\.)\s*', '', first_line, flags=re.IGNORECASE)
        formatted_question = f"<b>Q{current_q_num}. {first_line}</b>"
        options_html = ""
        if len(lines) > 1:
            options_html = "<br>" + "<br>".join([line.strip() for line in lines[1:]])
            
        formatted_html_parts.append(f"{formatted_question}{options_html}")
        current_q_num += 1
        
    return "<br><br>".join(formatted_html_parts)

def create_html_paper(ai_text, manual_text, manual_images, coaching, logo_data, details_dict, ai_q_count):
    split_marker = "[[BREAK]]"
    ai_questions, ai_answers = "", ""
    
    # 1. Process Text AI Questions
    if split_marker in ai_text:
        parts = ai_text.split(split_marker)
        ai_questions = parts[0].replace(chr(10), '<br>')
        ai_answers = parts[1].replace(chr(10), '<br>')
    else:
        ai_questions = ai_text.replace(chr(10), '<br>')

    # 2. Process Manual/Diagram Text (AUTO NUMBERING)
    manual_questions_html = ""
    current_count = ai_q_count
    if manual_text:
        start_from = current_count + 1
        formatted_manual = process_manual_text_auto_number(manual_text, start_from)
        prefix = "<br><br>" if current_count > 0 else ""
        manual_questions_html = f"{prefix}{formatted_manual}"
        # Update count based on how many manual questions were added
        current_count += len(re.split(r'\n\s*\n', manual_text.strip()))

    # 3. Process Images (Now placed nicely near their questions if possible)
    # Note: In this simple version, images still go to the end, but the text is generated by AI.
    # For true interleaving, we need a more complex data structure.
    manual_images_html = ""
    if manual_images:
        manual_images_html = "<br><br>"
        for img_file in manual_images:
            img_b64 = get_image_base64(img_file)
            # Using a generic label, as linking exact text to image in HTML is complex here
            manual_images_html += f"""
            <div class='question-box' style='margin-top: 20px; page-break-inside: avoid;'>
                <p><strong>Refer to the following figure for relevant questions:</strong></p>
                <img src='{img_b64}' style='max-width: 100%; max-height: 400px; border: 1px solid #ccc; padding: 5px; border-radius: 5px;'>
            </div>
            """

    final_body = ai_questions + manual_questions_html + manual_images_html

    if ai_answers:
        final_body += f"""
        <div class='page-break'></div>
        <div class='header'><h2>Answer Key</h2><p>{details_dict['Subject']} - {details_dict['Topic']}</p></div>
        <div class='content'>{ai_answers}</div>
        """

    logo_html = f'<img src="{logo_data}" class="logo">' if logo_data else ''
    css_style = """
        body { font-family: 'Roboto', sans-serif; padding: 40px; max-width: 900px; margin: auto; line-height: 1.5; }
        .main-container { border: 2px solid #000; padding: 30px; min-height: 950px; position: relative; }
        .header-container { display: flex; align-items: center; border-bottom: 2px double #000; padding-bottom: 15px; margin-bottom: 20px; }
        .logo { max-width: 100px; max-height: 100px; margin-right: 20px; }
        .header-text { flex-grow: 1; text-align: center; }
        .header-text h1 { margin: 0; font-size: 32px; text-transform: uppercase; color: #d32f2f; }
        .info-table { width: 100%; margin-top: 10px; border-collapse: collapse; }
        .info-table td { padding: 5px; font-weight: bold; border: 1px solid #ddd; }
        .question-box { margin-bottom: 15px; font-size: 16px; }
        .page-break { page-break-before: always; }
        .footer { position: absolute; bottom: 10px; width: 100%; text-align: center; font-size: 10px; color: #555; }
    """
    return f"<!DOCTYPE html><html><head><meta charset='UTF-8'><title>{details_dict['Topic']}</title><link href='https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari&family=Roboto&display=swap' rel='stylesheet'><style>{css_style}</style></head><body><div class='main-container'><div class='header-container'>{logo_html}<div class='header-text'><h1>{coaching}</h1></div></div><table class='info-table'><tr><td>Exam: {details_dict['Exam Name']}</td><td>Subject: {details_dict['Subject']}</td></tr><tr><td>Time: {details_dict['Time']}</td><td>Marks: {details_dict['Marks']}</td></tr><tr><td colspan='2' style='text-align:center; background-color:#eee;'>Topic: {details_dict['Topic']}</td></tr></table><div style='font-size:12px; font-style:italic; margin:15px 0; padding:8px; background:#f9f9f9; border-left:4px solid #444;'>Instructions: All questions are compulsory. / सभी प्रश्न अनिवार्य हैं।</div><div class='content'>{final_body}</div><div class='footer'>Created by PaperBanao.ai • Best of Luck!</div></div></body></html>"

# --- 4. UI Setup ---
st.markdown('<div class="main-header">📄 PaperBanao.ai</div>', unsafe_allow_html=True)

# --- SIDEBAR ---
with st.sidebar:
    st.header("⚙️ Control Panel")
    
    # API KEY SETUP
    st.markdown("### 🔑 API License")
    user_key = st.text_input("Enter Your API Key (Optional):", type="password")
    if user_key:
        api_key = user_key
        st.info("👤 Using: Personal Key")
    elif "GOOGLE_API_KEY" in st.secrets:
        api_key = st.secrets["GOOGLE_API_KEY"]
        st.success("✅ Using: Free Shared License")
    else:
        api_key = None
        st.error("❌ No License Found.")

    # MODEL SETUP (Common for both text and image generation)
    model_vision = None
    model_text = None
    if api_key:
        try:
            genai.configure(api_key=api_key)
            # Find best model (Gemini 1.5 Flash is best for both vision & text)
            chosen_model_name = "gemini-1.5-flash" # Defaulting to best option
            try:
                 models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
                 if "models/gemini-1.5-flash" not in models:
                     if "models/gemini-pro-vision" in models: chosen_model_name = "gemini-pro-vision" # Fallback for OLD keys
                     elif "models/gemini-pro" in models: chosen_model_name = "gemini-pro" # Text only fallback

            except: pass
            
            # Initialize models based on capabilities
            if "vision" in chosen_model_name or "1.5" in chosen_model_name:
                 model_vision = genai.GenerativeModel(chosen_model_name)
                 model_text = genai.GenerativeModel(chosen_model_name)
            else:
                 # Split models if using older gemini-pro/vision combo
                 model_text = genai.GenerativeModel("gemini-pro")
                 # Try finding a vision model specifically
                 try:
                    vision_models = [m.name for m in genai.list_models() if 'vision' in m.name]
                    if vision_models: model_vision = genai.GenerativeModel(vision_models[0])
                 except: pass

        except Exception as e: st.error(f"API Error: {e}")

    st.markdown("---")
    # EXAM DETAILS
    coaching_name = st.text_input("Institute Name:", value="Patna Success Classes")
    uploaded_logo = st.file_uploader("Upload Logo", type=['png', 'jpg'])
    final_logo = uploaded_logo if uploaded_logo else ("logo.png" if os.path.exists("logo.png") else None)
    exam_name = st.text_input("Exam Name:", value="Class 10 Unit Test")
    subject = st.text_input("Subject:", value="Science")
    topic = st.text_input("Topic:", value="Light")
    col1, col2 = st.columns(2)
    with col1: time_limit = st.text_input("Time:", value="45 Mins")
    with col2: max_marks = st.text_input("Marks:", value="20")
    
    st.markdown("---")
    # SECTION 1: TEXT AI QUESTIONS
    st.subheader("1️⃣ Text-Based AI Questions")
    num_questions = st.slider("Number of Questions:", 0, 50, 5)
    language = st.radio("Language:", ["Hindi", "English", "Bilingual"])
    
    st.markdown("---")
    # SECTION 2: NEW! DIAGRAM AI QUESTIONS
    st.subheader("2️⃣ Diagram-Based AI Questions (New!)")
    with st.expander("✨ Generate from Diagram", expanded=True):
        st.markdown('<div class="diagram-box">', unsafe_allow_html=True)
        st.caption("Upload a diagram and ask AI to make a question for it.")
        
        diagram_img_upload = st.file_uploader("Upload Diagram (One at a time):", type=['png', 'jpg', 'jpeg'], key="diagram_uploader")
        
        if diagram_img_upload:
            st.image(diagram_img_upload, caption="Preview", use_column_width=True)
            diagram_prompt = st.text_input("Instruction for AI (e.g., 'Ask about label A'):", key="diagram_prompt")
            
            if st.button("🧙‍♂️ Generate Question from Diagram"):
                if not model_vision:
                    st.error("❌ Vision Model not available with current API Key.")
                elif not diagram_prompt:
                    st.warning("⚠️ Please write an instruction first.")
                else:
                    with st.spinner("AI is looking at the diagram..."):
                        try:
                            # Prepare image for Gemini
                            img_pil = Image.open(diagram_img_upload)
                            
                            # Prompt structure
                            lang_hint = "in HINDI" if "Hindi" in language else "in ENGLISH"
                            full_prompt = [f"Based on this image, create a multiple choice question {lang_hint}. Instruction: {diagram_prompt}. Format: Question text on first line, then (A) Option1, (B) Option2 etc. on new lines. Do NOT add Q number.", img_pil]
                            
                            response = model_vision.generate_content(full_prompt)
                            generated_q_text = response.text.strip()
                            
                            # Add to session state (Memory)
                            # Add a blank line separator if needed
                            sep = "\n\n" if st.session_state.manual_text_content else ""
                            st.session_state.manual_text_content += sep + generated_q_text
                            # Store the image too
                            st.session_state.manual_uploaded_images.append(diagram_img_upload)
                            
                            st.success("✅ Question generated and added below! You can upload another now.")
                            # Force rerun to update the manual box below
                            st.rerun()
                            
                        except Exception as e:
                            st.error(f"Error generating from image: {e}")

        st.markdown('</div>', unsafe_allow_html=True)

    st.markdown("---")
    # SECTION 3: MANUAL REVIEW AREA
    with st.expander("3️⃣ Review & Edit Manual/Diagram Questions"):
        st.caption("AI generated diagram questions will appear here. You can also type manually.")
        # The text area is bound to session state variable
        manual_text = st.text_area("Question Editor (Auto-Numbering Active)", value=st.session_state.manual_text_content, height=250, key="manual_text_area_input")
        # Sync changes back to session state
        st.session_state.manual_text_content = manual_text
        
        # Display Images currently in memory
        if st.session_state.manual_uploaded_images:
             st.write(f"**Total Images Added:** {len(st.session_state.manual_uploaded_images)}")
        
        # Option to clear memory
        if st.button("🗑️ Clear All Manual/Diagram Data"):
            st.session_state.manual_text_content = ""
            st.session_state.manual_uploaded_images = []
            st.rerun()

    st.markdown("---")
    # FINAL GENERATE BUTTON
    btn_generate_final = st.button("🚀 Generate Final Paper PDF/HTML", type="primary")


# --- 5. MAIN LOGIC (FINAL GENERATION) ---
if btn_generate_final:
    if not api_key: st.warning("⚠️ API Key Required.")
    else:
        # --- PART A: Generate Text Questions ---
        ai_text_final = ""
        if num_questions > 0 and model_text:
            with st.spinner(f'🤖 Generating {num_questions} text questions...'):
                try:
                    lang_prompt = "HINDI (Devanagari)" if "Hindi" in language else "ENGLISH"
                    if "Bilingual" in language: lang_prompt = "ENGLISH followed by HINDI translation"
                    prompt = f"Create {num_questions} MCQ for '{topic}' ({subject}). Lang: {lang_prompt}. Format: <b>Q1. ?</b><br>(A)..<br> End with [[BREAK]] then Answer Key."
                    
                    # Simple retry logic
                    for i in range(2):
                        try:
                             response = model_text.generate_content(prompt)
                             ai_text_final = response.text
                             break
                        except: time.sleep(2)

                except Exception as e:
                    st.error(f"Text AI Error: {e}")

        # --- PART B: Combine with Manual/Diagram Data ---
        # Get data from session state
        final_manual_text = st.session_state.manual_text_content
        final_manual_images = st.session_state.manual_uploaded_images
        
        logo_b64 = get_image_base64(final_logo)
        details = { "Exam Name": exam_name, "Subject": subject, "Topic": topic, "Time": time_limit, "Marks": max_marks }
        
        # Create HTML
        final_html = create_html_paper(ai_text_final, final_manual_text, final_manual_images, coaching_name, logo_b64, details, num_questions)
        
        st.balloons()
        st.success("✅ Final Paper Ready!")
        st.download_button("📥 Download Final Paper (HTML)", final_html, f"{subject}_{topic}.html", "text/html")
